version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to pip repositories every weekday
      interval: "daily"
